### PR TITLE
Factor out the refresh token logic to allow people to call it on a client.

### PR DESCRIPTION
**Pull request by tomwilkie**
This saves us having to make a new client for each request, and the extra API call that entails.

### CODE REVIEW

**Comment by tomwilkie** [comment]
ping @FrenchBen

**Comment by FrenchBen** [comment]
LGTM thanks for the PR 👍

**Comment by ghiden** [comment]
@tomwilkie Could you tell me why we need the lock while setting header? I'm new to Go and trying to learn from experts.

**Comment by tomwilkie** [comment]
Not setting the header, getting and setting the auth field in the struct,
as it can be use concurrently.

**Comment by ghiden** [comment]
Thanks for your quick reply @tomwilkie

**Pull request merged**
